/*
 * GENERATED from spec/conformance/sqlite-cursor-stage-ownership.case.json.
 * Do not edit this file by hand. The conformance test binds every exported
 * byte/value back to the canonical cross-language fixture.
 */

export const SQLITE_CURSOR_SEAL_TEMP_TABLE_NAME = "ge_blr_cursor_seal";

export const SQLITE_CURSOR_SEAL_TEMP_TABLE_DDL = `CREATE TEMP TABLE ge_blr_cursor_seal (
  token_hash TEXT NOT NULL COLLATE BINARY,
  tenant_id TEXT NOT NULL COLLATE BINARY,
  kind TEXT NOT NULL,
  principal_hash TEXT NOT NULL,
  authorization_hash TEXT NOT NULL,
  stream_id TEXT,
  checkpoint_scope TEXT,
  request_scope_byte_length INTEGER NOT NULL,
  request_scope_blob_sha256 TEXT NOT NULL,
  page_size INTEGER NOT NULL,
  next_position INTEGER NOT NULL,
  snapshot_tail_sequence INTEGER,
  snapshot_tail_record_hash TEXT,
  snapshot_byte_length INTEGER NOT NULL,
  snapshot_blob_sha256 TEXT NOT NULL,
  created_at_ms INTEGER NOT NULL,
  expires_at_ms INTEGER NOT NULL,
  consumed_at_ms INTEGER,
  descriptor_hash TEXT NOT NULL,
  schema_identity_sha256 TEXT NOT NULL,
  authorization_ok INTEGER NOT NULL CHECK (authorization_ok IN (0, 1)),
  scope_ok INTEGER NOT NULL CHECK (scope_ok IN (0, 1)),
  blobs_canonical_ok INTEGER NOT NULL CHECK (blobs_canonical_ok IN (0, 1)),
  position_ok INTEGER NOT NULL CHECK (position_ok IN (0, 1)),
  clock_ok INTEGER NOT NULL CHECK (clock_ok IN (0, 1)),
  catalog_ok INTEGER NOT NULL CHECK (catalog_ok IN (0, 1)),
  shape_ok INTEGER NOT NULL CHECK (shape_ok IN (0, 1)),
  event_binding_ok INTEGER NOT NULL CHECK (event_binding_ok IN (0, 1)),
  checkpoint_binding_ok INTEGER NOT NULL CHECK (checkpoint_binding_ok IN (0, 1)),
  seal_eligible INTEGER NOT NULL CHECK (seal_eligible IN (0, 1)),
  PRIMARY KEY (token_hash, tenant_id)
) STRICT, WITHOUT ROWID`;

export const SQLITE_CURSOR_SEAL_TEMP_TABLE_DDL_SHA256 =
  "032db65e1e8c11d90ed27fc6a6e2cab130d1bf33c7d688381f5666379c52b84a";

export const SQLITE_CURSOR_SEAL_SCHEMA_SQL =
  `CREATE TABLE${SQLITE_CURSOR_SEAL_TEMP_TABLE_DDL.slice("CREATE TEMP TABLE".length)}`;

export const SQLITE_CURSOR_SEAL_TABLE_LIST = Object.freeze({
  name: SQLITE_CURSOR_SEAL_TEMP_TABLE_NAME,
  type: "table",
  ncol: 30,
  wr: 1,
  strict: 1,
} as const);

export interface SQLiteCursorSealXinfoColumn {
  readonly cid: number;
  readonly name: string;
  readonly type: "INTEGER" | "TEXT";
  readonly notnull: 0 | 1;
  readonly dfltValue: null;
  readonly pk: 0 | 1 | 2;
  readonly hidden: 0;
}

const COLUMNS = [
  ["token_hash", "TEXT", 1, 1],
  ["tenant_id", "TEXT", 1, 2],
  ["kind", "TEXT", 1, 0],
  ["principal_hash", "TEXT", 1, 0],
  ["authorization_hash", "TEXT", 1, 0],
  ["stream_id", "TEXT", 0, 0],
  ["checkpoint_scope", "TEXT", 0, 0],
  ["request_scope_byte_length", "INTEGER", 1, 0],
  ["request_scope_blob_sha256", "TEXT", 1, 0],
  ["page_size", "INTEGER", 1, 0],
  ["next_position", "INTEGER", 1, 0],
  ["snapshot_tail_sequence", "INTEGER", 0, 0],
  ["snapshot_tail_record_hash", "TEXT", 0, 0],
  ["snapshot_byte_length", "INTEGER", 1, 0],
  ["snapshot_blob_sha256", "TEXT", 1, 0],
  ["created_at_ms", "INTEGER", 1, 0],
  ["expires_at_ms", "INTEGER", 1, 0],
  ["consumed_at_ms", "INTEGER", 0, 0],
  ["descriptor_hash", "TEXT", 1, 0],
  ["schema_identity_sha256", "TEXT", 1, 0],
  ["authorization_ok", "INTEGER", 1, 0],
  ["scope_ok", "INTEGER", 1, 0],
  ["blobs_canonical_ok", "INTEGER", 1, 0],
  ["position_ok", "INTEGER", 1, 0],
  ["clock_ok", "INTEGER", 1, 0],
  ["catalog_ok", "INTEGER", 1, 0],
  ["shape_ok", "INTEGER", 1, 0],
  ["event_binding_ok", "INTEGER", 1, 0],
  ["checkpoint_binding_ok", "INTEGER", 1, 0],
  ["seal_eligible", "INTEGER", 1, 0],
] as const;

export const SQLITE_CURSOR_SEAL_XINFO: readonly SQLiteCursorSealXinfoColumn[] =
  Object.freeze(COLUMNS.map(([name, type, notnull, pk], cid) => Object.freeze({
    cid,
    name,
    type,
    notnull,
    dfltValue: null,
    pk,
    hidden: 0,
  })));
