"""Provider and tool adapters, ``adapter-contract/v1alpha1``.

Three adapters ship here: the deterministic mock (fully featured), the generic
HTTP tool adapter (transport injected, no network fallback) and the shell
adapter (declaration and argument construction only — execution refuses while no
isolation provider exists).

No OpenAI, Anthropic or Gemini client exists in this package.  Those kinds name
intended boundary shapes in the contract; no request has ever been sent to any
of them by this code.  This package performs no network access and spawns no
process: it imports no ``socket``, ``subprocess``, ``http.client``,
``urllib.request``, ``requests`` or ``httpx``, and ``tests/test_adapter_no_host_io.py``
proves it statically and at runtime.
"""

from .base import (
    Adapter,
    AdapterCallOptions,
    AdapterOutcome,
    AdapterOutcomeMisuse,
    AdapterResponse,
    CancelSignal,
    envelope_from_contract_error,
    is_aborted,
    narrow_side_effect,
    ok,
    refused,
    run_preflight,
    structured_output_document,
)
from .circuit import CircuitBreaker, circuit_fold
from .contract import (
    ADAPTER_CAPABILITIES,
    ADAPTER_ERROR_CODES,
    ADAPTER_KINDS,
    CAPABILITY_GATED_RESOURCES,
    CAPABILITY_IMPLICATIONS,
    DENIAL_REASONS,
    FINISH_REASONS,
    MOCK_ONLY_CAPABILITIES,
    MODEL_ADAPTER_KINDS,
    REPORTABLE_RESOURCES,
    RESOURCE_UNITS,
    SAFE_INTEGER_MAX,
    SIDE_EFFECT_ORDER,
    STREAM_FRAME_KINDS,
    TAXONOMY_FACTS,
    USAGE_TRUSTS,
    USAGE_UNIT_RESOURCES,
    CapabilityGatedResource,
    CapabilityImplication,
    MockOnlyCapability,
    TaxonomyFacts,
    derive_budget_cost_state,
    derive_ledger_action,
    derive_usage_disposition,
    escalates_side_effect,
    is_non_routable_host,
    requires_in_doubt_record,
    side_effect_permits_retry,
    taxonomy_facts,
)
from .descriptor import validate_descriptor, validate_descriptor_against_budget_policy
from .envelope import normalized_adapter_error, validate_error_envelope
from .errors import AdapterContractError, fail, is_adapter_contract_error
from .http_adapter import (
    DEFAULT_HTTP_STATUS_CODES,
    DEFAULT_MAX_REDIRECTS,
    HttpAdapter,
    HttpCallSpec,
    HttpRequestInit,
    HttpRequestPlan,
    HttpResponse,
    HttpTransport,
    HttpTransportError,
    HttpTransportTimeout,
    classify_http_status,
    create_http_adapter,
    parse_retry_after_ms,
)
from .mock_adapter import (
    DEFAULT_TEXT,
    AdapterStream,
    MockAdapter,
    MockOutcome,
    create_mock_adapter,
    plan_frames,
    plan_meters,
)
from .ordering import compare_unicode_code_points, is_sorted_by_code_point, sort_by_code_point
from .preflight import capability_failure_message, preflight
from .retry import computed_backoff_ms, retry_decision
from .shell_adapter import (
    SHELL_EXECUTION_BLOCKING_TASK,
    SHELL_EXECUTION_CAPABILITY_DOMAIN,
    SHELL_EXECUTION_DENIAL_REASON,
    SHELL_EXECUTION_ISOLATION_CODE,
    SHELL_EXECUTION_REFUSAL_MESSAGE,
    ProcessLaunchPlan,
    ProcessLaunchSpec,
    ShellAdapter,
    create_shell_adapter,
)
from .stream import normalize_stream
from .tools import validate_tool_calls
from .types import (
    ADAPTER_API_VERSION,
    ADAPTER_CONTRACT_VERSION,
    AdapterBounds,
    AdapterCapability,
    AdapterCapture,
    AdapterCircuitPolicy,
    AdapterDescriptor,
    AdapterDocumentError,
    AdapterErrorCode,
    AdapterErrorEnvelope,
    AdapterKind,
    AdapterRequest,
    AdapterRetryPolicy,
    AdapterUsage,
    BudgetCostState,
    CircuitProjection,
    CircuitState,
    CircuitStep,
    DenialReason,
    EffectDisposition,
    EgressTarget,
    FinishReason,
    McpCall,
    McpProfile,
    ModelToolCall,
    NetworkProfile,
    NormalizedErrorOutcome,
    NormalizedStream,
    NormalizedToolCalls,
    NormalizedUsage,
    PreflightOutcome,
    ProcessCall,
    ProcessProfile,
    ProviderMetricDeclaration,
    ProviderQuantity,
    ProviderSafeField,
    ReportableResource,
    RequestAttachment,
    RetryDecision,
    SideEffectClass,
    StreamFrame,
    ToolCallResponse,
    ToolDefinition,
    UsageDisposition,
    UsageQuantity,
    UsageTrust,
)
from .usage import compose_usage, validate_usage

__all__ = [
    "ADAPTER_API_VERSION",
    "ADAPTER_CAPABILITIES",
    "ADAPTER_CONTRACT_VERSION",
    "ADAPTER_ERROR_CODES",
    "ADAPTER_KINDS",
    "CAPABILITY_GATED_RESOURCES",
    "CAPABILITY_IMPLICATIONS",
    "DEFAULT_HTTP_STATUS_CODES",
    "DEFAULT_MAX_REDIRECTS",
    "DEFAULT_TEXT",
    "DENIAL_REASONS",
    "FINISH_REASONS",
    "MOCK_ONLY_CAPABILITIES",
    "MODEL_ADAPTER_KINDS",
    "REPORTABLE_RESOURCES",
    "RESOURCE_UNITS",
    "SAFE_INTEGER_MAX",
    "SHELL_EXECUTION_BLOCKING_TASK",
    "SHELL_EXECUTION_CAPABILITY_DOMAIN",
    "SHELL_EXECUTION_DENIAL_REASON",
    "SHELL_EXECUTION_ISOLATION_CODE",
    "SHELL_EXECUTION_REFUSAL_MESSAGE",
    "SIDE_EFFECT_ORDER",
    "STREAM_FRAME_KINDS",
    "TAXONOMY_FACTS",
    "USAGE_TRUSTS",
    "USAGE_UNIT_RESOURCES",
    "Adapter",
    "AdapterBounds",
    "AdapterCallOptions",
    "AdapterCapability",
    "AdapterCapture",
    "AdapterCircuitPolicy",
    "AdapterContractError",
    "AdapterDescriptor",
    "AdapterDocumentError",
    "AdapterErrorCode",
    "AdapterErrorEnvelope",
    "AdapterKind",
    "AdapterOutcome",
    "AdapterOutcomeMisuse",
    "AdapterRequest",
    "AdapterResponse",
    "AdapterRetryPolicy",
    "AdapterStream",
    "AdapterUsage",
    "BudgetCostState",
    "CancelSignal",
    "CapabilityGatedResource",
    "CapabilityImplication",
    "CircuitBreaker",
    "CircuitProjection",
    "CircuitState",
    "CircuitStep",
    "DenialReason",
    "EffectDisposition",
    "EgressTarget",
    "FinishReason",
    "HttpAdapter",
    "HttpCallSpec",
    "HttpRequestInit",
    "HttpRequestPlan",
    "HttpResponse",
    "HttpTransport",
    "HttpTransportError",
    "HttpTransportTimeout",
    "McpCall",
    "McpProfile",
    "MockAdapter",
    "MockOnlyCapability",
    "MockOutcome",
    "ModelToolCall",
    "NetworkProfile",
    "NormalizedErrorOutcome",
    "NormalizedStream",
    "NormalizedToolCalls",
    "NormalizedUsage",
    "PreflightOutcome",
    "ProcessCall",
    "ProcessLaunchPlan",
    "ProcessLaunchSpec",
    "ProcessProfile",
    "ProviderMetricDeclaration",
    "ProviderQuantity",
    "ProviderSafeField",
    "ReportableResource",
    "RequestAttachment",
    "RetryDecision",
    "ShellAdapter",
    "SideEffectClass",
    "StreamFrame",
    "TaxonomyFacts",
    "ToolCallResponse",
    "ToolDefinition",
    "UsageDisposition",
    "UsageQuantity",
    "UsageTrust",
    "capability_failure_message",
    "circuit_fold",
    "classify_http_status",
    "compare_unicode_code_points",
    "compose_usage",
    "computed_backoff_ms",
    "create_http_adapter",
    "create_mock_adapter",
    "create_shell_adapter",
    "derive_budget_cost_state",
    "derive_ledger_action",
    "derive_usage_disposition",
    "envelope_from_contract_error",
    "escalates_side_effect",
    "fail",
    "is_aborted",
    "is_adapter_contract_error",
    "is_non_routable_host",
    "is_sorted_by_code_point",
    "narrow_side_effect",
    "normalize_stream",
    "normalized_adapter_error",
    "ok",
    "parse_retry_after_ms",
    "plan_frames",
    "plan_meters",
    "preflight",
    "refused",
    "requires_in_doubt_record",
    "retry_decision",
    "run_preflight",
    "side_effect_permits_retry",
    "sort_by_code_point",
    "structured_output_document",
    "taxonomy_facts",
    "validate_descriptor",
    "validate_descriptor_against_budget_policy",
    "validate_error_envelope",
    "validate_tool_calls",
    "validate_usage",
]
